site_name: py-rbush
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.tabs

repo_url: https://github.com/lebr0nli/py-rbush
repo_name: lebr0nli/py-rbush

nav:
  - Introduction: index.md
  - User Guide: user_guide.md
  - Developer Guide: developer_guide.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
